# Generated by Django 3.1.2 on 2020-10-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='id_no',
            field=models.IntegerField(),
        ),
    ]
