# Generated by Django 3.1.2 on 2020-10-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201019_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='id_no',
            field=models.IntegerField(unique=True),
        ),
    ]
