# Generated by Django 3.1.2 on 2020-11-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_filesadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesAdmin',
        ),
    ]
