# Generated by Django 3.1.2 on 2020-10-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201019_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='id_no',
        ),
    ]
