# Generated by Django 3.1.2 on 2020-11-12 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_filesadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('qpuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='QPUser')),
                ('quizid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.quiz', verbose_name='QuizId')),
            ],
        ),
    ]
