# Generated by Django 3.1.2 on 2020-10-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_school_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='standard_name',
            field=models.CharField(max_length=50),
        ),
    ]
