# Generated by Django 3.1.2 on 2020-10-19 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201019_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpuser',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='qpuser',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.standard', verbose_name='Standard'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.school', verbose_name='School'),
        ),
    ]
