# Generated by Django 3.1.2 on 2020-11-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_score_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='is_multiple_choice',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
