# Generated by Django 3.1.2 on 2020-11-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_multiplechoicequestion_is_multiple_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoicequestion',
            old_name='is_multiple_choice',
            new_name='is_multiple_ans',
        ),
    ]
