# Generated by Django 3.1.2 on 2020-11-16 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201116_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
