# Generated by Django 3.1.2 on 2020-10-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201020_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.standard', verbose_name='Assigned to'),
        ),
    ]
