# Generated by Django 3.1.2 on 2020-10-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201020_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpuser',
            name='standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.standard', verbose_name='Stadard'),
        ),
        migrations.AlterField(
            model_name='qpuser',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='qpuser',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.section', verbose_name='Section'),
        ),
    ]
