# Generated by Django 3.1.2 on 2020-10-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201020_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_description',
            field=models.CharField(default=models.CharField(max_length=200), max_length=200),
        ),
    ]
