# Generated by Django 3.1.2 on 2020-10-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_quiz_quiz_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_description',
            field=models.CharField(default='Description', max_length=200),
        ),
    ]
