# Generated by Django 3.1.2 on 2020-10-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201020_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_link',
            field=models.CharField(default='quiz', max_length=100),
        ),
    ]
