# Generated by Django 3.1.3 on 2021-01-03 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_loggedinuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qpuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='QPUser')),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('flash_card_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.flashcardgroup', verbose_name='Flashcard Group')),
            ],
        ),
    ]
