# Generated by Django 3.1.2 on 2020-10-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_quiz_quiz_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_link',
        ),
    ]
