# Generated by Django 3.1.2 on 2020-10-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_quiz_quiz_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='question_no',
            field=models.IntegerField(default=1),
        ),
    ]
