# Generated by Django 3.1.2 on 2020-10-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_multiplechoicequestion_question_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='question_no',
            field=models.IntegerField(unique=True),
        ),
    ]
